-- =====================================================================
-- KeviN · ล็อก search_path ของสามฟังก์ชันที่เหลือ
--
-- advisor `function_search_path_mutable` — ฟังก์ชันที่ไม่ได้ตั้ง `search_path`
-- ใช้ค่าของ role ที่เรียก · คนที่ตั้ง search_path ของตัวเองแล้วมีตารางชื่อซ้ำ
-- ในสคีมาที่มาก่อน `public` จะทำให้ฟังก์ชันไปอ่านตารางผิดตัวได้
--
-- ⚠️ ทั้งสามตัวเป็น **security invoker** (ทำงานด้วยสิทธิ์ของคนเรียก) จึงเสี่ยง
--    น้อยกว่า `security definer` มาก — แต่ตั้งให้ครบถูกกว่าปล่อยไว้
--
-- ใช้ `alter function ... set` **ไม่ใช่ `create or replace`** เพื่อ**ไม่ต้องแตะ body**
-- ที่ผ่านการวัดมาแล้ว · ไม่มีทางพิมพ์ตกหล่นระหว่างคัดลอก
--
-- ตรวจ body ก่อนแล้วว่าไม่มีตัวไหนเรียกของนอก `public` เลย
-- (ไม่มี `extensions.` / `net.` / `vault.` / `auth.` / pgcrypto) จึงล็อกได้ปลอดภัย
-- · ยืนยันหลังรันด้วยการ**เรียกจริงทั้งสองตัว** ไม่ใช่ดูแค่ว่า DDL สำเร็จ
--
-- ─────────────────────────────────────────────────────────────────────
-- ⚠️ สิ่งที่ **จงใจไม่แก้**: advisor `extension_in_public` ของ `pg_net`
--
--    ท่ามาตรฐานคือ `alter extension pg_net set schema extensions;`
--    **แต่ cron ของการเตือนเรียก `net.http_post(...)` ทุกนาที** · การย้าย
--    สคีมาของ extension มีโอกาสทำให้ชื่อนั้นหาไม่เจอ แล้ว**การเตือนหยุดส่ง
--    แบบเงียบ ๆ** ซึ่งเป็นความพังที่แพงที่สุดของระบบนี้
--
--    ที่ได้กลับมาคือ lint หายไปหนึ่งบรรทัด · pg_net ถูก Supabase ติดตั้งไว้
--    แบบนี้เป็นค่าเริ่มต้นอยู่แล้ว · **ไม่คุ้มความเสี่ยง — ปล่อยไว้โดยรู้ตัว**
-- =====================================================================
alter function public.touch_updated_at()               set search_path = public, pg_temp;
alter function public.schedule_occurrences(date, date) set search_path = public, pg_temp;
alter function public.calendar_entries(date, date)     set search_path = public, pg_temp;
